sonar.projectKey=Vanhhssahh_App_estandares_y_metricas
sonar.organization=jennpmod-conectando-sqlite

# Nombre y versión que se mostrarán en SonarQube
sonar.projectName=App_estandares_y_metricas
sonar.projectVersion=1.0

# Rutas del código fuente
sonar.sources=app/src/main/java

# Codificación de caracteres
sonar.sourceEncoding=UTF-8
